### ISSUE TITLE
problems compiling javascript

### ISSUE THREAD

**Issue by profbdcohen** [moodleou/save-answersheets#3]
I tried to follow the instructions; I downloaded the text file from Moodle and also the javascript files from Github. When I ran the script it gave me an error:
Line 1
Char 1
Error: Invalid Character
Code: 800a03f6
Source: microsoft jscript compilation error

I'm not a programmer; I'm trying to use this to generate pdfs for grading purposes in my biology classes.
Thanks in Advance!
Brian

**Comment by timhunt** [comment]
If you dont want to runt he script, there is no need to compile it. You should be able to run it. However, to use it you need a basic understanding of Node JS.
