### ISSUE TITLE
"Your session has timed out. Please login again" and page.SetCookie(...)

### ISSUE THREAD

**Issue by PeterMacGonagan** [moodleou/save-answersheets#5]
Hello,

Everything seems to work perfectly BUT...
All my PDF files "responses.pdf" contains "Your session has timed out. Please log in again".
I veryfied the cookie contains in the .txt file and I decode it with a Base64 decoder. The value which has returned are the same that in Chrome. 
I've installed Visual Studio Code to debug the script and I can observe that these values are well decoded by the script...

So, what to do? I think that page.setCookie doesn't work? Could you help me, please?

Thank you in advance.

**Comment by timhunt** [comment]
Sorry, don't know why this is happening. The script works with the Open University's sign-in system. What sort of sign-in system are you using?

I think you need to experiment, can you get a single curl command (or similar) that will download a page from your Moodle site. If you can make that work on its own, then that might suggest what is wrong with the script.

**Comment by timhunt** [comment]
No further feedback, so I am closing this. If you can provide more information, please comment, and I will reopen.
